version: "2"
services:
  ixo-web:
    environment:
      - REACT_APP_BLOCKCHAIN_NODE_URL=http://blockchain_qa.ixo.world:46657
      - REACT_APP_BLOCK_SYNC_URL=https://explorer_qa.ixo.world
      - REACT_APP_IXO_WORLD_ORIGIN=https://qa.ixo.world
      - REACT_APP_KYC_LINK=https://staging.ixo.frctls.com
      - REACT_APP_IXO_TOKEN_CONTRACT_ADDRESS="0x24cc742b89ba0f113e368571cb10107a0c27023d"
      - REACT_APP_PROJECT_REGISTRY_CONTRACT_ADDRESS="0x9b1c7a77e5227fd17b4bb5fa73557ec14a1fc266"