version: 2.1

# --------------------------------
# common : base
# --------------------------------

orbs:
  node: circleci/node@5.0.3

# --------------------------------
# env
# --------------------------------

uat_in_app_environment: &uat_in_app_environment
  name: 'UAT in app env variables'
  command: |
    echo 'REACT_APP_CHAIN_ID=pandora-8' >> .env
    echo 'REACT_APP_BLOCK_SYNC_URL=https://blocksync-pandora.ixo.earth' >> .env
    echo 'REACT_APP_BLOCK_SYNC_GRAPHQL=https://blocksync-pandora.ixo.earth/graphiql' >> .env
    echo 'REACT_APP_BLOCK_SCAN_URL=https://blockscan-pandora.ixo.earth/' >> .env
    echo 'REACT_APP_GAIA_URL=https://testnet.ixo.earth/rest/' >> .env
    echo 'REACT_APP_RPC_URL=https://testnet.ixo.earth/rpc/' >> .env
    echo 'REACT_APP_PDS_URL=https://cellnode-pandora.ixo.earth/' >> .env
    echo 'REACT_APP_CONFIG_RELAYER_URL=https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/configs/testzone/app-config.json' >> .env
    echo 'REACT_APP_CONFIG_SCHEMA_URL=https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/configs/testzone/config.json' >> .env
    echo 'REACT_APP_CONFIG_EXCHANGE_URL=https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/configs/testzone/exchange.json' >> .env
    echo 'REACT_APP_CONFIG_ASSETLIST_URL=https://raw.githubusercontent.com/ixofoundation/ixo-webclient/dev/configs/testzone/asset-list.json' >> .env
    echo 'REACT_APP_IXO_WORLD_ORIGIN=https://uat.ixo.world' >> .env
    echo 'REACT_APP_KYC_LINK=https://signup.ixo.world' >> .env
    echo 'REACT_APP_ASSISTANT_URL=https://bf-ixo-world.development.agents.botfront.cloud' >> .env
    echo 'REACT_APP_ENTITY_VERSION=1.0.0' >> .env
    echo 'REACT_APP_ENTITY_PAGE_VERSION=1.0.0' >> .env
    echo 'REACT_APP_EMBEDLY_KEY=fa2749f731a54587820cf4fcfaa53d30' >> .env
    echo 'REACT_APP_GOOGLE_API_KEY=AIzaSyDpFiV_PlNEos214wqgOCUpkezMStOyheA' >> .env
    echo 'REACT_APP_RELAYER_NODE=did:sov:Rmb6Rd1CU6k74FM2xzy6Do' >> .env
    echo 'REACT_APP_FEE_PER_CLAIM_FEE=0.6' >> .env
    echo 'REACT_APP_FEE_PER_EVALUATION=0.4' >> .env
    echo 'REACT_APP_FEE_OVERHEAD=1.3' >> .env

# --------------------------------
# jobs
# --------------------------------

jobs:
  test:
    executor:
      name: node/default
      tag: '16.18.1'
    parallelism: 5
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: *uat_in_app_environment
      - run:
          command: |
            shopt -s globstar
            TEST=$(ls src/**/*.test.{ts,tsx} | circleci tests split --split-by=name)
            yarn test $TEST
          name: Run tests

# --------------------------------
# workflows
# --------------------------------

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - dev
                - impact
  uat_test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - dev
  prod_test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - impact
